#!/usr/bin/env bash
set -Eeuo pipefail

cd "$(dirname "$0")"
helm repo add --force-update bitnami https://charts.bitnami.com/bitnami
helm template templates-api-etcd bitnami/etcd -f ./values.yaml -n templates-api > etcd.yaml

# Replace root password by ENV
sed  -i'.bak' -e's/etcd-root-password: ".*"/etcd-root-password: "$ETCD_ROOT_PASSWORD_BASE64"/g' etcd.yaml

# Replace replica count by ENV
sed  -i'.bak' -e's/replicas: .*/replicas: $ETCD_REPLICA_COUNT/g' etcd.yaml
sed  -i'.bak' -e's/value: "templates-api-etcd-0=.*"/value: "$ETCD_INITIAL_CLUSTER"/g' etcd.yaml

# Modify labels generated by Helm
sed  -i'.bak' -e's/app.kubernetes.io\/instance: templates-api-etcd/app: templates-api-etcd/g' etcd.yaml
sed  -i'.bak' -e'/app.kubernetes.io\/name/d' etcd.yaml
sed  -i'.bak' -e'/app.kubernetes.io\/managed-by/d' etcd.yaml
sed  -i'.bak' -e'/helm\.sh\/chart/d' etcd.yaml
