#!/usr/bin/env bash
set -Eeuo pipefail

cd "$(dirname "$0")"
helm template templates-api-etcd bitnami/etcd -f ./values.yaml > etcd.yaml

# Replace root password by ENV
sed -i 's/etcd-root-password: ".*"/etcd-root-password: "$ETCD_ROOT_PASSWORD_BASE64"/g' etcd.yaml

# Replace replica count by ENV
sed -i 's/replicas: .*/replicas: $ETCD_REPLICA_COUNT/g' etcd.yaml
sed -i 's/value: "templates-api-etcd-0=.*"/value: "$ETCD_INITIAL_CLUSTER"/g' etcd.yaml

# Modify labels generated by Helm
sed -i 's/app.kubernetes.io\/instance: templates-api-etcd/app: templates-api-etcd/g' etcd.yaml
sed -i '/app.kubernetes.io\/name/d' etcd.yaml
sed -i '/app.kubernetes.io\/managed-by/d' etcd.yaml
sed -i '/helm.sh\/chart/d' etcd.yaml
