// Code generated by ent, DO NOT EDIT.

package model

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/branch"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/configuration"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/key"
	"github.com/keboola/keboola-sdk-go/v2/pkg/keboola"
)

// BranchCreate is the builder for creating a Branch entity.
type BranchCreate struct {
	config
	mutation *BranchMutation
	hooks    []Hook
}

// SetBranchID sets the "branchID" field.
func (_c *BranchCreate) SetBranchID(v keboola.BranchID) *BranchCreate {
	_c.mutation.SetBranchID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *BranchCreate) SetName(v string) *BranchCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *BranchCreate) SetDescription(v string) *BranchCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetIsDefault sets the "isDefault" field.
func (_c *BranchCreate) SetIsDefault(v bool) *BranchCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BranchCreate) SetID(v key.BranchKey) *BranchCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddConfigurationIDs adds the "configurations" edge to the Configuration entity by IDs.
func (_c *BranchCreate) AddConfigurationIDs(ids ...key.ConfigurationKey) *BranchCreate {
	_c.mutation.AddConfigurationIDs(ids...)
	return _c
}

// AddConfigurations adds the "configurations" edges to the Configuration entity.
func (_c *BranchCreate) AddConfigurations(v ...*Configuration) *BranchCreate {
	ids := make([]key.ConfigurationKey, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddConfigurationIDs(ids...)
}

// Mutation returns the BranchMutation object of the builder.
func (_c *BranchCreate) Mutation() *BranchMutation {
	return _c.mutation
}

// Save creates the Branch in the database.
func (_c *BranchCreate) Save(ctx context.Context) (*Branch, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BranchCreate) SaveX(ctx context.Context) *Branch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BranchCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BranchCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BranchCreate) check() error {
	if _, ok := _c.mutation.BranchID(); !ok {
		return &ValidationError{Name: "branchID", err: errors.New(`model: missing required field "Branch.branchID"`)}
	}
	if v, ok := _c.mutation.BranchID(); ok {
		if err := branch.BranchIDValidator(int(v)); err != nil {
			return &ValidationError{Name: "branchID", err: fmt.Errorf(`model: validator failed for field "Branch.branchID": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`model: missing required field "Branch.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := branch.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`model: validator failed for field "Branch.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`model: missing required field "Branch.description"`)}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "isDefault", err: errors.New(`model: missing required field "Branch.isDefault"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := branch.IDValidator(v.String()); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`model: validator failed for field "Branch.id": %w`, err)}
		}
	}
	return nil
}

func (_c *BranchCreate) sqlSave(ctx context.Context) (*Branch, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*key.BranchKey); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BranchCreate) createSpec() (*Branch, *sqlgraph.CreateSpec) {
	var (
		_node = &Branch{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(branch.Table, sqlgraph.NewFieldSpec(branch.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.BranchID(); ok {
		_spec.SetField(branch.FieldBranchID, field.TypeInt, value)
		_node.BranchID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(branch.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(branch.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(branch.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if nodes := _c.mutation.ConfigurationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   branch.ConfigurationsTable,
			Columns: []string{branch.ConfigurationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configuration.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BranchCreateBulk is the builder for creating many Branch entities in bulk.
type BranchCreateBulk struct {
	config
	err      error
	builders []*BranchCreate
}

// Save creates the Branch entities in the database.
func (_c *BranchCreateBulk) Save(ctx context.Context) ([]*Branch, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Branch, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BranchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BranchCreateBulk) SaveX(ctx context.Context) []*Branch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BranchCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BranchCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
