// Code generated by ent, DO NOT EDIT.

package model

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/branch"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/configuration"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/key"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/predicate"
)

// BranchUpdate is the builder for updating Branch entities.
type BranchUpdate struct {
	config
	hooks    []Hook
	mutation *BranchMutation
}

// Where appends a list predicates to the BranchUpdate builder.
func (_u *BranchUpdate) Where(ps ...predicate.Branch) *BranchUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *BranchUpdate) SetName(v string) *BranchUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BranchUpdate) SetNillableName(v *string) *BranchUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BranchUpdate) SetDescription(v string) *BranchUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BranchUpdate) SetNillableDescription(v *string) *BranchUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// AddConfigurationIDs adds the "configurations" edge to the Configuration entity by IDs.
func (_u *BranchUpdate) AddConfigurationIDs(ids ...key.ConfigurationKey) *BranchUpdate {
	_u.mutation.AddConfigurationIDs(ids...)
	return _u
}

// AddConfigurations adds the "configurations" edges to the Configuration entity.
func (_u *BranchUpdate) AddConfigurations(v ...*Configuration) *BranchUpdate {
	ids := make([]key.ConfigurationKey, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConfigurationIDs(ids...)
}

// Mutation returns the BranchMutation object of the builder.
func (_u *BranchUpdate) Mutation() *BranchMutation {
	return _u.mutation
}

// ClearConfigurations clears all "configurations" edges to the Configuration entity.
func (_u *BranchUpdate) ClearConfigurations() *BranchUpdate {
	_u.mutation.ClearConfigurations()
	return _u
}

// RemoveConfigurationIDs removes the "configurations" edge to Configuration entities by IDs.
func (_u *BranchUpdate) RemoveConfigurationIDs(ids ...key.ConfigurationKey) *BranchUpdate {
	_u.mutation.RemoveConfigurationIDs(ids...)
	return _u
}

// RemoveConfigurations removes "configurations" edges to Configuration entities.
func (_u *BranchUpdate) RemoveConfigurations(v ...*Configuration) *BranchUpdate {
	ids := make([]key.ConfigurationKey, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConfigurationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BranchUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BranchUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BranchUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BranchUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BranchUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := branch.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`model: validator failed for field "Branch.name": %w`, err)}
		}
	}
	return nil
}

func (_u *BranchUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(branch.Table, branch.Columns, sqlgraph.NewFieldSpec(branch.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(branch.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(branch.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.ConfigurationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   branch.ConfigurationsTable,
			Columns: []string{branch.ConfigurationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configuration.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConfigurationsIDs(); len(nodes) > 0 && !_u.mutation.ConfigurationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   branch.ConfigurationsTable,
			Columns: []string{branch.ConfigurationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configuration.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfigurationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   branch.ConfigurationsTable,
			Columns: []string{branch.ConfigurationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configuration.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{branch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BranchUpdateOne is the builder for updating a single Branch entity.
type BranchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BranchMutation
}

// SetName sets the "name" field.
func (_u *BranchUpdateOne) SetName(v string) *BranchUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BranchUpdateOne) SetNillableName(v *string) *BranchUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BranchUpdateOne) SetDescription(v string) *BranchUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BranchUpdateOne) SetNillableDescription(v *string) *BranchUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// AddConfigurationIDs adds the "configurations" edge to the Configuration entity by IDs.
func (_u *BranchUpdateOne) AddConfigurationIDs(ids ...key.ConfigurationKey) *BranchUpdateOne {
	_u.mutation.AddConfigurationIDs(ids...)
	return _u
}

// AddConfigurations adds the "configurations" edges to the Configuration entity.
func (_u *BranchUpdateOne) AddConfigurations(v ...*Configuration) *BranchUpdateOne {
	ids := make([]key.ConfigurationKey, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConfigurationIDs(ids...)
}

// Mutation returns the BranchMutation object of the builder.
func (_u *BranchUpdateOne) Mutation() *BranchMutation {
	return _u.mutation
}

// ClearConfigurations clears all "configurations" edges to the Configuration entity.
func (_u *BranchUpdateOne) ClearConfigurations() *BranchUpdateOne {
	_u.mutation.ClearConfigurations()
	return _u
}

// RemoveConfigurationIDs removes the "configurations" edge to Configuration entities by IDs.
func (_u *BranchUpdateOne) RemoveConfigurationIDs(ids ...key.ConfigurationKey) *BranchUpdateOne {
	_u.mutation.RemoveConfigurationIDs(ids...)
	return _u
}

// RemoveConfigurations removes "configurations" edges to Configuration entities.
func (_u *BranchUpdateOne) RemoveConfigurations(v ...*Configuration) *BranchUpdateOne {
	ids := make([]key.ConfigurationKey, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConfigurationIDs(ids...)
}

// Where appends a list predicates to the BranchUpdate builder.
func (_u *BranchUpdateOne) Where(ps ...predicate.Branch) *BranchUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BranchUpdateOne) Select(field string, fields ...string) *BranchUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Branch entity.
func (_u *BranchUpdateOne) Save(ctx context.Context) (*Branch, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BranchUpdateOne) SaveX(ctx context.Context) *Branch {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BranchUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BranchUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BranchUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := branch.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`model: validator failed for field "Branch.name": %w`, err)}
		}
	}
	return nil
}

func (_u *BranchUpdateOne) sqlSave(ctx context.Context) (_node *Branch, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(branch.Table, branch.Columns, sqlgraph.NewFieldSpec(branch.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`model: missing "Branch.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, branch.FieldID)
		for _, f := range fields {
			if !branch.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("model: invalid field %q for query", f)}
			}
			if f != branch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(branch.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(branch.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.ConfigurationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   branch.ConfigurationsTable,
			Columns: []string{branch.ConfigurationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configuration.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConfigurationsIDs(); len(nodes) > 0 && !_u.mutation.ConfigurationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   branch.ConfigurationsTable,
			Columns: []string{branch.ConfigurationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configuration.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfigurationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   branch.ConfigurationsTable,
			Columns: []string{branch.ConfigurationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configuration.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Branch{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{branch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
