// Code generated by ent, DO NOT EDIT.

package model

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keboola/go-utils/pkg/orderedmap"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/configuration"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/predicate"
)

// ConfigurationUpdate is the builder for updating Configuration entities.
type ConfigurationUpdate struct {
	config
	hooks    []Hook
	mutation *ConfigurationMutation
}

// Where appends a list predicates to the ConfigurationUpdate builder.
func (_u *ConfigurationUpdate) Where(ps ...predicate.Configuration) *ConfigurationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ConfigurationUpdate) SetName(v string) *ConfigurationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ConfigurationUpdate) SetNillableName(v *string) *ConfigurationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ConfigurationUpdate) SetDescription(v string) *ConfigurationUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ConfigurationUpdate) SetNillableDescription(v *string) *ConfigurationUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIsDisabled sets the "isDisabled" field.
func (_u *ConfigurationUpdate) SetIsDisabled(v bool) *ConfigurationUpdate {
	_u.mutation.SetIsDisabled(v)
	return _u
}

// SetNillableIsDisabled sets the "isDisabled" field if the given value is not nil.
func (_u *ConfigurationUpdate) SetNillableIsDisabled(v *bool) *ConfigurationUpdate {
	if v != nil {
		_u.SetIsDisabled(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ConfigurationUpdate) SetContent(v *orderedmap.OrderedMap) *ConfigurationUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// Mutation returns the ConfigurationMutation object of the builder.
func (_u *ConfigurationUpdate) Mutation() *ConfigurationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConfigurationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigurationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConfigurationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigurationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigurationUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := configuration.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`model: validator failed for field "Configuration.name": %w`, err)}
		}
	}
	if _u.mutation.ParentCleared() && len(_u.mutation.ParentIDs()) > 0 {
		return errors.New(`model: clearing a required unique edge "Configuration.parent"`)
	}
	return nil
}

func (_u *ConfigurationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configuration.Table, configuration.Columns, sqlgraph.NewFieldSpec(configuration.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(configuration.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(configuration.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDisabled(); ok {
		_spec.SetField(configuration.FieldIsDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(configuration.FieldContent, field.TypeJSON, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configuration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConfigurationUpdateOne is the builder for updating a single Configuration entity.
type ConfigurationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConfigurationMutation
}

// SetName sets the "name" field.
func (_u *ConfigurationUpdateOne) SetName(v string) *ConfigurationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ConfigurationUpdateOne) SetNillableName(v *string) *ConfigurationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ConfigurationUpdateOne) SetDescription(v string) *ConfigurationUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ConfigurationUpdateOne) SetNillableDescription(v *string) *ConfigurationUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIsDisabled sets the "isDisabled" field.
func (_u *ConfigurationUpdateOne) SetIsDisabled(v bool) *ConfigurationUpdateOne {
	_u.mutation.SetIsDisabled(v)
	return _u
}

// SetNillableIsDisabled sets the "isDisabled" field if the given value is not nil.
func (_u *ConfigurationUpdateOne) SetNillableIsDisabled(v *bool) *ConfigurationUpdateOne {
	if v != nil {
		_u.SetIsDisabled(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ConfigurationUpdateOne) SetContent(v *orderedmap.OrderedMap) *ConfigurationUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// Mutation returns the ConfigurationMutation object of the builder.
func (_u *ConfigurationUpdateOne) Mutation() *ConfigurationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ConfigurationUpdate builder.
func (_u *ConfigurationUpdateOne) Where(ps ...predicate.Configuration) *ConfigurationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConfigurationUpdateOne) Select(field string, fields ...string) *ConfigurationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Configuration entity.
func (_u *ConfigurationUpdateOne) Save(ctx context.Context) (*Configuration, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigurationUpdateOne) SaveX(ctx context.Context) *Configuration {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConfigurationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigurationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigurationUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := configuration.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`model: validator failed for field "Configuration.name": %w`, err)}
		}
	}
	if _u.mutation.ParentCleared() && len(_u.mutation.ParentIDs()) > 0 {
		return errors.New(`model: clearing a required unique edge "Configuration.parent"`)
	}
	return nil
}

func (_u *ConfigurationUpdateOne) sqlSave(ctx context.Context) (_node *Configuration, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configuration.Table, configuration.Columns, sqlgraph.NewFieldSpec(configuration.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`model: missing "Configuration.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, configuration.FieldID)
		for _, f := range fields {
			if !configuration.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("model: invalid field %q for query", f)}
			}
			if f != configuration.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(configuration.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(configuration.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDisabled(); ok {
		_spec.SetField(configuration.FieldIsDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(configuration.FieldContent, field.TypeJSON, value)
	}
	_node = &Configuration{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configuration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
