// Code generated by ent, DO NOT EDIT.

package model

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/keboola/go-utils/pkg/orderedmap"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/branch"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/configuration"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/key"
	"github.com/keboola/keboola-sdk-go/v2/pkg/keboola"
)

// Configuration is the model entity for the Configuration schema.
type Configuration struct {
	config `json:"-"`
	// ID of the ent.
	ID key.ConfigurationKey `json:"id,omitempty"`
	// BranchID holds the value of the "branchID" field.
	BranchID keboola.BranchID `json:"branchID,omitempty"`
	// ComponentID holds the value of the "componentID" field.
	ComponentID keboola.ComponentID `json:"componentID,omitempty"`
	// ConfigID holds the value of the "configID" field.
	ConfigID keboola.ConfigID `json:"configID,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// IsDisabled holds the value of the "isDisabled" field.
	IsDisabled bool `json:"isDisabled,omitempty"`
	// Content holds the value of the "content" field.
	Content *orderedmap.OrderedMap `json:"content,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConfigurationQuery when eager-loading is set.
	Edges                ConfigurationEdges `json:"edges"`
	configuration_parent *key.BranchKey
	selectValues         sql.SelectValues
}

// ConfigurationEdges holds the relations/edges for other nodes in the graph.
type ConfigurationEdges struct {
	// Parent holds the value of the parent edge.
	Parent *Branch `json:"parent,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConfigurationEdges) ParentOrErr() (*Branch, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: branch.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Configuration) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case configuration.FieldContent:
			values[i] = new([]byte)
		case configuration.FieldID:
			values[i] = new(key.ConfigurationKey)
		case configuration.FieldIsDisabled:
			values[i] = new(sql.NullBool)
		case configuration.FieldBranchID:
			values[i] = new(sql.NullInt64)
		case configuration.FieldComponentID, configuration.FieldConfigID, configuration.FieldName, configuration.FieldDescription:
			values[i] = new(sql.NullString)
		case configuration.ForeignKeys[0]: // configuration_parent
			values[i] = &sql.NullScanner{S: new(key.BranchKey)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Configuration fields.
func (_m *Configuration) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case configuration.FieldID:
			if value, ok := values[i].(*key.ConfigurationKey); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case configuration.FieldBranchID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field branchID", values[i])
			} else if value.Valid {
				_m.BranchID = keboola.BranchID(value.Int64)
			}
		case configuration.FieldComponentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field componentID", values[i])
			} else if value.Valid {
				_m.ComponentID = keboola.ComponentID(value.String)
			}
		case configuration.FieldConfigID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field configID", values[i])
			} else if value.Valid {
				_m.ConfigID = keboola.ConfigID(value.String)
			}
		case configuration.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case configuration.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case configuration.FieldIsDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isDisabled", values[i])
			} else if value.Valid {
				_m.IsDisabled = value.Bool
			}
		case configuration.FieldContent:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Content); err != nil {
					return fmt.Errorf("unmarshal field content: %w", err)
				}
			}
		case configuration.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field configuration_parent", values[i])
			} else if value.Valid {
				_m.configuration_parent = new(key.BranchKey)
				*_m.configuration_parent = *value.S.(*key.BranchKey)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Configuration.
// This includes values selected through modifiers, order, etc.
func (_m *Configuration) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the Configuration entity.
func (_m *Configuration) QueryParent() *BranchQuery {
	return NewConfigurationClient(_m.config).QueryParent(_m)
}

// Update returns a builder for updating this Configuration.
// Note that you need to call Configuration.Unwrap() before calling this method if this Configuration
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Configuration) Update() *ConfigurationUpdateOne {
	return NewConfigurationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Configuration entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Configuration) Unwrap() *Configuration {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("model: Configuration is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Configuration) String() string {
	var builder strings.Builder
	builder.WriteString("Configuration(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("branchID=")
	builder.WriteString(fmt.Sprintf("%v", _m.BranchID))
	builder.WriteString(", ")
	builder.WriteString("componentID=")
	builder.WriteString(fmt.Sprintf("%v", _m.ComponentID))
	builder.WriteString(", ")
	builder.WriteString("configID=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("isDisabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDisabled))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(fmt.Sprintf("%v", _m.Content))
	builder.WriteByte(')')
	return builder.String()
}

// Configurations is a parsable slice of Configuration.
type Configurations []*Configuration
