// Code generated by ent, DO NOT EDIT.

package model

import (
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/branch"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/configuration"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/model/configurationrow"
	"github.com/keboola/keboola-as-code/internal/pkg/platform/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	branchMixin := schema.Branch{}.Mixin()
	branchMixinFields0 := branchMixin[0].Fields()
	_ = branchMixinFields0
	branchFields := schema.Branch{}.Fields()
	_ = branchFields
	// branchDescBranchID is the schema descriptor for branchID field.
	branchDescBranchID := branchMixinFields0[1].Descriptor()
	// branch.BranchIDValidator is a validator for the "branchID" field. It is called by the builders before save.
	branch.BranchIDValidator = branchDescBranchID.Validators[0].(func(int) error)
	// branchDescName is the schema descriptor for name field.
	branchDescName := branchFields[0].Descriptor()
	// branch.NameValidator is a validator for the "name" field. It is called by the builders before save.
	branch.NameValidator = branchDescName.Validators[0].(func(string) error)
	// branchDescID is the schema descriptor for id field.
	branchDescID := branchMixinFields0[0].Descriptor()
	// branch.IDValidator is a validator for the "id" field. It is called by the builders before save.
	branch.IDValidator = branchDescID.Validators[0].(func(string) error)
	configurationMixin := schema.Configuration{}.Mixin()
	configurationMixinFields0 := configurationMixin[0].Fields()
	_ = configurationMixinFields0
	configurationFields := schema.Configuration{}.Fields()
	_ = configurationFields
	// configurationDescBranchID is the schema descriptor for branchID field.
	configurationDescBranchID := configurationMixinFields0[1].Descriptor()
	// configuration.BranchIDValidator is a validator for the "branchID" field. It is called by the builders before save.
	configuration.BranchIDValidator = configurationDescBranchID.Validators[0].(func(int) error)
	// configurationDescComponentID is the schema descriptor for componentID field.
	configurationDescComponentID := configurationMixinFields0[2].Descriptor()
	// configuration.ComponentIDValidator is a validator for the "componentID" field. It is called by the builders before save.
	configuration.ComponentIDValidator = configurationDescComponentID.Validators[0].(func(string) error)
	// configurationDescConfigID is the schema descriptor for configID field.
	configurationDescConfigID := configurationMixinFields0[3].Descriptor()
	// configuration.ConfigIDValidator is a validator for the "configID" field. It is called by the builders before save.
	configuration.ConfigIDValidator = configurationDescConfigID.Validators[0].(func(string) error)
	// configurationDescName is the schema descriptor for name field.
	configurationDescName := configurationFields[0].Descriptor()
	// configuration.NameValidator is a validator for the "name" field. It is called by the builders before save.
	configuration.NameValidator = configurationDescName.Validators[0].(func(string) error)
	// configurationDescIsDisabled is the schema descriptor for isDisabled field.
	configurationDescIsDisabled := configurationFields[2].Descriptor()
	// configuration.DefaultIsDisabled holds the default value on creation for the isDisabled field.
	configuration.DefaultIsDisabled = configurationDescIsDisabled.Default.(bool)
	// configurationDescID is the schema descriptor for id field.
	configurationDescID := configurationMixinFields0[0].Descriptor()
	// configuration.IDValidator is a validator for the "id" field. It is called by the builders before save.
	configuration.IDValidator = configurationDescID.Validators[0].(func(string) error)
	configurationrowMixin := schema.ConfigurationRow{}.Mixin()
	configurationrowMixinFields0 := configurationrowMixin[0].Fields()
	_ = configurationrowMixinFields0
	configurationrowFields := schema.ConfigurationRow{}.Fields()
	_ = configurationrowFields
	// configurationrowDescBranchID is the schema descriptor for branchID field.
	configurationrowDescBranchID := configurationrowMixinFields0[1].Descriptor()
	// configurationrow.BranchIDValidator is a validator for the "branchID" field. It is called by the builders before save.
	configurationrow.BranchIDValidator = configurationrowDescBranchID.Validators[0].(func(int) error)
	// configurationrowDescComponentID is the schema descriptor for componentID field.
	configurationrowDescComponentID := configurationrowMixinFields0[2].Descriptor()
	// configurationrow.ComponentIDValidator is a validator for the "componentID" field. It is called by the builders before save.
	configurationrow.ComponentIDValidator = configurationrowDescComponentID.Validators[0].(func(string) error)
	// configurationrowDescConfigID is the schema descriptor for configID field.
	configurationrowDescConfigID := configurationrowMixinFields0[3].Descriptor()
	// configurationrow.ConfigIDValidator is a validator for the "configID" field. It is called by the builders before save.
	configurationrow.ConfigIDValidator = configurationrowDescConfigID.Validators[0].(func(string) error)
	// configurationrowDescRowID is the schema descriptor for rowID field.
	configurationrowDescRowID := configurationrowMixinFields0[4].Descriptor()
	// configurationrow.RowIDValidator is a validator for the "rowID" field. It is called by the builders before save.
	configurationrow.RowIDValidator = configurationrowDescRowID.Validators[0].(func(string) error)
	// configurationrowDescName is the schema descriptor for name field.
	configurationrowDescName := configurationrowFields[0].Descriptor()
	// configurationrow.NameValidator is a validator for the "name" field. It is called by the builders before save.
	configurationrow.NameValidator = configurationrowDescName.Validators[0].(func(string) error)
	// configurationrowDescIsDisabled is the schema descriptor for isDisabled field.
	configurationrowDescIsDisabled := configurationrowFields[2].Descriptor()
	// configurationrow.DefaultIsDisabled holds the default value on creation for the isDisabled field.
	configurationrow.DefaultIsDisabled = configurationrowDescIsDisabled.Default.(bool)
	// configurationrowDescID is the schema descriptor for id field.
	configurationrowDescID := configurationrowMixinFields0[0].Descriptor()
	// configurationrow.IDValidator is a validator for the "id" field. It is called by the builders before save.
	configurationrow.IDValidator = configurationrowDescID.Validators[0].(func(string) error)
}
