#!/usr/bin/env bash
set -Eeuo pipefail

# Required ENVs
: ${BUILD_BUILDID?"Missing BUILD_BUILDID"}
: ${RELEASE_RELEASENAME?"Missing RELEASE_RELEASENAME"}
: ${KEBOOLA_STACK?"Missing KEBOOLA_STACK"}
: ${HOSTNAME_SUFFIX?"Missing HOSTNAME_SUFFIX"}
: ${TEMPLATES_API_REPOSITORY?"Missing TEMPLATES_API_REPOSITORY"}
: ${TEMPLATES_API_IMAGE_TAG?"Missing TEMPLATES_API_IMAGE_TAG"}
: ${TEMPLATES_API_REPLICAS?"Missing TEMPLATES_API_REPLICAS"}
: ${TEMPLATES_API_ETCD_REPLICAS?"Missing TEMPLATES_API_ETCD_REPLICAS"}

COMMIT_HASH=$(git rev-parse HEAD)
export COMMIT_HASH

export RELEASE_ID="$BUILD_BUILDID-$RELEASE_RELEASENAME"

./"$CLOUD_PROVIDER".sh
