# Build container
FROM golang:1.18 AS buildContainer
WORKDIR /app
COPY . .
#flags: -s -w to remove symbol table and debug info
RUN make tools
RUN make build-templates-api

# Production container
FROM alpine
RUN apk add -U --no-cache ca-certificates git

COPY --from=buildContainer /app/target/templates-api/server /app/server
WORKDIR /app

ENV HOST 0.0.0.0
ENV PORT 8000
EXPOSE 8000

CMD ["/app/server", "--http-host=0.0.0.0", "--http-port=8000"]
