name: 'Release CLI'
description: 'Release CLI to AWS bucket'
inputs:
  tag:
    description: Tag version
    required: true
  version:
    description: Version
    required: true
  github_token:
    description: Github token.
    required: true
  apple_account_password:
    description: Apple account password
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials to CLI Assets Account
      id: credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::455460941449:role/cli-dist-release
        aws-region: us-east-1
        output-credentials: true

    - name: Release
      shell: bash
      run: make release
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CLI_DIST_BASE_URL: "https://cli-dist.keboola.com"
        CLI_DIST_AWS_REGION: us-east-1
        CLI_DIST_AWS_BUCKET_NAME: cli-dist-keboola-com
        CLI_DIST_AWS_ACCESS_KEY_ID: ${{ steps.credentials.outputs.aws-access-key-id }}
        CLI_DIST_AWS_SECRET_ACCESS_KEY: ${{ steps.credentials.outputs.aws-secret-access-key }}
        CLI_DIST_AWS_SESSION_TOKEN: ${{ steps.credentials.outputs.aws-session-token }}
        DEB_KEY_PRIVATE_PATH: /tmp/keys/deb.key
        RPM_KEY_PRIVATE_PATH: /tmp/keys/rpm.key
        APK_KEY_PRIVATE_PATH: /tmp/keys/apk.key
        APPLE_ACCOUNT_PASSWORD: ${{ inputs.apple_account_password }}
        VERSION: ${{ inputs.version }}

    - name: Upload artifact to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.github_token }}
        file: target/gh-release/*
        tag: ${{ inputs.tag }}
        overwrite: true
        file_glob: true
        prerelease: true

    - name: Create Homebrew formulae
      shell: bash
      run: |
        mkdir target/homebrew
        export DARWIN_ARM_TARGET_SHA256=$(openssl dgst -sha256  target/gh-release/*darwin_arm64.zip | cut -f 2 -d ' ' )
        export DARWIN_AMD_TARGET_SHA256=$(openssl dgst -sha256  target/gh-release/*darwin_amd64.zip | cut -f 2 -d ' ' )
        export LINUX_ARM_TARGET_SHA256=$(openssl dgst -sha256   target/gh-release/*linux_armv6.zip  | cut -f 2 -d ' ' )
        export LINUX_ARM64_TARGET_SHA256=$(openssl dgst -sha256 target/gh-release/*linux_arm64.zip  | cut -f 2 -d ' ' )
        export LINUX_AMD_TARGET_SHA256=$(openssl dgst -sha256   target/gh-release/*linux_amd64.zip  | cut -f 2 -d ' ' )
        envsubst < build/package/homebrew/homebrew.template.rb > target/homebrew/keboola-cli.rb
        cat target/homebrew/keboola-cli.rb

    - name: Upload Homebrew formulae
      uses: actions/upload-artifact@v4
      with:
        name: homebrew-formulae
        path: target/homebrew/keboola-cli.rb
        if-no-files-found: error
        retention-days: 1

    - name: Upload Scoop manifest
      uses: actions/upload-artifact@v4
      with:
        name: scoop-manifest
        path: target/scoop/keboola-cli.json
        if-no-files-found: error
        retention-days: 1

