---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buffer-worker
  namespace: $NAMESPACE
  labels:
    app: buffer-worker
data:
  storageApiHost: "connection.$HOSTNAME_SUFFIX"
  keboolaStack: "$KEBOOLA_STACK"
  keboolaRevision: "$RELEASE_ID"
