---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: buffer-api-pdb
  namespace: $NAMESPACE
  labels:
    app: buffer-api
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: buffer-api
