// nolint: gochecknoglobals
package openapi

import (
	"embed"
)

// Fs OpenAPI files are generated by "make generate-code"
//
//go:embed openapi.json
//go:embed openapi.yaml
//go:embed openapi3.json
//go:embed openapi3.yaml
var Fs embed.FS
