# Extends values from the common directory

# Run defragmentation each 2 hours
defragmentation:
  cronjob:
    schedule: "0 */2 * * *"

startFromSnapshot:
  enabled: false
  existingClaim: "stream-etcd-snapshotter"
  snapshotFilename: "db-2025-04-03_14-15"

disasterRecovery:
  enabled: true
  cronjob:
    schedule: "*/5 * * * *"
    podLabels:
      stream-etcd-client: "true"
  pvc:
    existingClaim: "stream-etcd-snapshotter"
    size: 2Gi
