---
kind: Service
apiVersion: v1
metadata:
  name: stream-api
  namespace: $NAMESPACE
  labels:
    app: stream-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: stream-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
