keboola_stack            = "keboola-prod-kac-assets"
bucket_name              = "cli-dist-keboola-com"
github_oidc_provider_arn = "arn:aws:iam::455460941449:oidc-provider/token.actions.githubusercontent.com"
aws_acm_certificate_arn  = ""
distribution_domain_name = "cli-dist.keboola.com"
