package storageapi

import (
	"fmt"
	"net/http"

	"github.com/spf13/cast"

	. "github.com/keboola/keboola-as-code/internal/pkg/api/client"
	"github.com/keboola/keboola-as-code/internal/pkg/model"
)

// GetBranchRequest https://keboola.docs.apiary.io/#reference/development-branches/branch-manipulation/branch-detail
func GetBranchRequest(branchId model.BranchId) Request[*model.Branch] {
	return newRequest(&model.Branch{}).
		SetMethod(http.MethodGet).
		SetUrl("dev-branches/{branchId}").
		SetPathParam("branchId", branchId.String())
}

// CreateBranchRequest https://keboola.docs.apiary.io/#reference/development-branches/branches/create-branch
func CreateBranchRequest(branch *model.Branch) Request[*model.Job] {
	// Id is autogenerated
	if branch.Id != 0 {
		panic(fmt.Errorf("branch id is set but it should be auto-generated"))
	}

	// Default branch cannot be created
	if branch.IsDefault {
		panic(fmt.Errorf("default branch cannot be created"))
	}

	return newRequest(&model.Job{}).
		SetMethod(http.MethodPost).
		SetUrl("dev-branches").
		SetFormBody(map[string]string{
			"name":        branch.Name,
			"description": branch.Description,
		})
}

// CreateBranchRequestSync https://keboola.docs.apiary.io/#reference/development-branches/branches/create-branch
func CreateBranchRequestSync(branch *model.Branch) Request[*model.Branch] {
	// Create request
	request := a.
		NewRequest(http.MethodPost, "dev-branches").
		SetFormBody(map[string]string{
			"name":        branch.Name,
			"description": branch.Description,
		}).
		SetResult(job)

	request.OnSuccess(waitForJob(a, request, job, func(response *http.Response) {
		// Set branch id from the job results
		branch.Id = model.BranchId(cast.ToInt(job.Results["id"]))
	}))

	return request
}

// UpdateBranchRequest https://keboola.docs.apiary.io/#reference/development-branches/branches/update-branch
func UpdateBranchRequest(branch *model.Branch, changed model.ChangedFields) Request[*model.Branch] {
	// Id is required
	if branch.Id == 0 {
		panic("branch id must be set")
	}

	// Data
	all := map[string]string{
		"description": branch.Description,
	}

	// Name of the default branch cannot be changed
	if !branch.IsDefault {
		all["name"] = branch.Name
	}

	// Create request
	return newRequest(branch).
		SetMethod(http.MethodPut).
		SetUrl("dev-branches/{branchId}").
		SetPathParam("branchId", branch.Id.String()).
		SetFormBody(getChangedValues(all, changed))
}

// ListBranchesRequest https://keboola.docs.apiary.io/#reference/development-branches/branches/list-branches
func ListBranchesRequest() Request[[]*model.Branch] {
	branches := make([]*model.Branch, 0)
	return newRequest(branches).
		SetMethod(http.MethodGet).
		SetUrl("dev-branches")
}

// DeleteBranchRequest https://keboola.docs.apiary.io/#reference/development-branches/branch-manipulation/delete-branch
func DeleteBranchRequest(key model.BranchKey) Request[*model.Job] {
	return newRequest(&model.Job{}).
		SetMethod(http.MethodDelete).
		SetUrl("dev-branches/{branchId}").
		SetPathParam("branchId", key.Id.String())
}

// DeleteBranchRequestSync https://keboola.docs.apiary.io/#reference/development-branches/branch-manipulation/delete-branch
func DeleteBranchRequestSync(key model.BranchKey) *http.Request {
	job := &model.Job{}
	request := a.
		NewRequest(http.MethodDelete, "dev-branches/{branchId}").
		SetPathParam("branchId", key.Id.String()).
		SetResult(job)
	request.OnSuccess(waitForJob(a, request, job, nil))
	return request
}

// ListBranchMetadataRequest https://keboola.docs.apiary.io/#reference/metadata/development-branch-metadata/list
func ListBranchMetadataRequest(branchId model.BranchId) Request[[]Metadata] {
	return newRequest(make([]Metadata, 0)).
		SetMethod(http.MethodGet).
		SetUrl("branch/{branchId}/metadata").
		SetPathParam("branchId", branchId.String())
}

// AppendBranchMetadataRequest https://keboola.docs.apiary.io/#reference/metadata/development-branch-metadata/create-or-update
func AppendBranchMetadataRequest(branch *model.Branch) Request[NoResult] {
	// Empty, we have nothing to append
	if len(branch.Metadata) == 0 {
		return nil
	}

	formBody := make(map[string]string)
	i := 0
	for k, v := range branch.Metadata {
		formBody[fmt.Sprintf("metadata[%d][key]", i)] = k
		formBody[fmt.Sprintf("metadata[%d][value]", i)] = v
		i++
	}

	return newRequest(NoResult{}).
		SetMethod(http.MethodPost).
		SetUrl("branch/{branchId}/metadata").
		SetPathParam("branchId", branch.Id.String()).
		SetFormBody(formBody)
}

func DeleteBranchMetadataRequest(branchId model.BranchId, metaId string) Request[NoResult] {
	return newRequest(NoResult{}).
		SetMethod(http.MethodDelete).
		SetUrl("branch/{branchId}/metadata/{metadataId}").
		SetPathParam("branchId", branchId.String()).
		SetPathParam("metadataId", metaId)
}
