name: 'Install Go and tools'
description: 'Install Go and tools'
runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false

    - name: Load Go tools cache
      uses: ./.github/actions/go-tools-cache
