---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: templates-api
  namespace: $NAMESPACE
  labels:
    app: templates-api
    releaseId: $RELEASE_ID
spec:
  replicas: $TEMPLATES_API_REPLICAS
  selector:
    matchLabels:
      app: templates-api
  template:
    metadata:
      labels:
        app: templates-api
        releaseId: $RELEASE_ID
        templates-api-etcd-client: "true"
        tags.datadoghq.com/env: "$KEBOOLA_STACK"
        tags.datadoghq.com/service: "templates-api"
        tags.datadoghq.com/version: "$RELEASE_ID"
      annotations:
        log: "true"
        ad.datadoghq.com/tags: '{"git.commit.sha": "$COMMIT_HASH", "git.repository_url": "https://github.com/keboola/keboola-as-code"}'
        ad.datadoghq.com/templates-api.checks: |
          {
            "openmetrics": {
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:9000/metrics",
                  "metrics": [".*"]
                }
              ]
            }
          }
    spec:
      containers:
        - name: templates-api
          image: $TEMPLATES_API_REPOSITORY:$TEMPLATES_API_IMAGE_TAG
          resources:
            requests:
              cpu: "200m"
              memory: "768Mi"
            limits:
              memory: "768Mi"
          ports:
            - containerPort: 8000 # API
            - containerPort: 9000 # metrics
          env:
            # 80% of the resources.limits.memory
            - name: GOMEMLIMIT
              value: "550MiB"
            - name: TEMPLATES_API_STORAGE_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: templates-api
                  key: storageApiHost
            - name: TEMPLATES_API_PUBLIC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: templates-api
                  key: templatesApiHost
            - name: TEMPLATES_API_ETCD_ENDPOINT
              value: templates-api-etcd.templates-api.svc.cluster.local:2379
            - name: TEMPLATES_API_ETCD_USERNAME
              value: root
            - name: TEMPLATES_API_ETCD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: templates-api-etcd
                  key: etcd-root-password
            - name: TEMPLATES_API_ETCD_NAMESPACE
              value: templates-api
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_ANALYTICS_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
          startupProbe:
            httpGet:
              path: /health-check
              port: 8000
              httpHeaders:
                - name: Host
                  value: KubernetesStartupProbe
            initialDelaySeconds: 10
            periodSeconds: 1
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /health-check
              port: 8000
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe
            periodSeconds: 10
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8000
              httpHeaders:
                - name: Host
                  value: KubernetesLivenessProbe
            periodSeconds: 10
            failureThreshold: 3
      tolerations:
        - key: app
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        nodepool: main
