---
kind: Service
apiVersion: v1
metadata:
  name: templates-api
  namespace: templates-api
  labels:
    app: templates-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: templates-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
