---
kind: Job
apiVersion: batch/v1
metadata:
  name: benchmark
  namespace: buffer-benchmark
  labels:
    app: buffer-benchmark
spec:
  template:
    metadata:
      labels:
        app: load-test
        buffer-etcd-client: "true"
        tags.datadoghq.com/env: "$KEBOOLA_STACK"
        tags.datadoghq.com/service: "load-test"
        tags.datadoghq.com/version: "$RELEASE_ID"
      annotations:
        log: "true"
    spec:
      terminationGracePeriodSeconds: 300
      restartPolicy: Never
      containers:
        - name: benchmark
          image: docker.io/keboolabot/buffer-benchmark:latest
          command: ["k6"]
          args: ["run", "--out", "statsd", "/benchmarks/buffer-api/cases/groupon.js"]
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
          env:
            # 80% of the resources.limits.memory 8125
            - name: GOMEMLIMIT
              value: "400MiB"
            - name: BENCHMARK_API_HOST
              value: "https://buffer.$HOSTNAME_SUFFIX"
            - name: BENCHMARK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: benchmark
                  key: api-token
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_STATSD_PORT
              value: "8125"
            - name: K6_STATSD_ADDR
              value: $(DD_AGENT_HOST):$(DD_STATSD_PORT)
            - name: K6_STATSD_ENABLE_TAGS
              value: "true"
            - name: BENCHMARK_MAX_VIRTUAL_USERS
              value: "100"
            - name: BENCHMARK_PARALLEL_REQS_PER_USER
              value: "10"
            - name: BENCHMARK_RAMPING_DURATION
              value: "5m"
            - name: BENCHMARK_STABLE_RATE_DURATION
              value: "5m"
      tolerations:
        - key: app
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        nodepool: main
