---
apiVersion: v1
kind: Secret
metadata:
  name: benchmark
  namespace: buffer-benchmark
  labels:
    app: buffer-benchmark
data:
  api-token: "$BENCHMARK_API_TOKEN_BASE64"
  etcd-password: "$ETCD_PASSWORD_BASE64"
