name: 'Load Go cache'
description: 'Load Go build cache'
inputs:
  key:
    description: Cache key
    required: true
env:
  CACHE_VERSION: v7
runs:
  using: "composite"
  steps:
    - name: Use GNU tar instead BSD tar
      if: runner.os == 'Windows'
      shell: bash
      run: echo 'C:\Program Files\Git\usr\bin' >> $GITHUB_PATH

    - name: Load Go cache
      uses: actions/cache@v4
      if: runner.os == 'Windows'
      with:
        path: |
          ~\go\pkg
          ~\go\bin
          ~\AppData\Local\golangci-lint
        key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-{{ env.CACHE_VERSION }}-${{ inputs.key }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-{{ env.CACHE_VERSION }}-
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-{{ env.CACHE_VERSION }}-${{ inputs.key }}-

    - name: Load Go cache
      uses: actions/cache@v4
      if: runner.os != 'Windows'
      with:
        path: |
          ~/go/pkg
          ~/go/bin
          ~/.cache/golangci-lint
          ~/Library/Caches/golangci-lint
        key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-{{ env.CACHE_VERSION }}-${{ inputs.key }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-{{ env.CACHE_VERSION }}-
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-{{ env.CACHE_VERSION }}-${{ inputs.key }}-
