name: 'Load Go cache'
description: 'Load Go build cache'
inputs:
  key:
    description: Cache key
    required: true
runs:
  using: "composite"
  steps:
    - name: Use GNU tar instead BSD tar
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == 'Windows' ]]; then
          echo 'C:\Program Files\Git\usr\bin' >> $GITHUB_PATH
        fi
    - name: Load Go cache
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~\go\pkg\mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~\AppData\Local\go-build
          ~/.cache/golangci-lint
          ~/Library/Caches/golangci-lint
          ~\AppData\Local\golangci-lint
        key: ${{ runner.os }}-go-v2-${{ inputs.key }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-v2-
          ${{ runner.os }}-go-v2-${{ inputs.key }}-
