// Code generated by ent, DO NOT EDIT.

package branch

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the branch type in the database.
	Label = "branch"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBranchID holds the string denoting the branchid field in the database.
	FieldBranchID = "branch_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldIsDefault holds the string denoting the isdefault field in the database.
	FieldIsDefault = "is_default"
	// EdgeConfigurations holds the string denoting the configurations edge name in mutations.
	EdgeConfigurations = "configurations"
	// Table holds the table name of the branch in the database.
	Table = "branches"
	// ConfigurationsTable is the table that holds the configurations relation/edge.
	ConfigurationsTable = "configurations"
	// ConfigurationsInverseTable is the table name for the Configuration entity.
	// It exists in this package in order to avoid circular dependency with the "configuration" package.
	ConfigurationsInverseTable = "configurations"
	// ConfigurationsColumn is the table column denoting the configurations relation/edge.
	ConfigurationsColumn = "configuration_parent"
)

// Columns holds all SQL columns for branch fields.
var Columns = []string{
	FieldID,
	FieldBranchID,
	FieldName,
	FieldDescription,
	FieldIsDefault,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BranchIDValidator is a validator for the "branchID" field. It is called by the builders before save.
	BranchIDValidator func(int) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Branch queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBranchID orders the results by the branchID field.
func ByBranchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBranchID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByIsDefault orders the results by the isDefault field.
func ByIsDefault(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDefault, opts...).ToFunc()
}

// ByConfigurationsCount orders the results by configurations count.
func ByConfigurationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newConfigurationsStep(), opts...)
	}
}

// ByConfigurations orders the results by configurations terms.
func ByConfigurations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConfigurationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newConfigurationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConfigurationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ConfigurationsTable, ConfigurationsColumn),
	)
}
