// Code generated by ent, DO NOT EDIT.

package branch

const (
	// Label holds the string label denoting the branch type in the database.
	Label = "branch"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBranchID holds the string denoting the branchid field in the database.
	FieldBranchID = "branch_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldIsDefault holds the string denoting the isdefault field in the database.
	FieldIsDefault = "is_default"
	// EdgeConfigurations holds the string denoting the configurations edge name in mutations.
	EdgeConfigurations = "configurations"
	// Table holds the table name of the branch in the database.
	Table = "branches"
	// ConfigurationsTable is the table that holds the configurations relation/edge.
	ConfigurationsTable = "configurations"
	// ConfigurationsInverseTable is the table name for the Configuration entity.
	// It exists in this package in order to avoid circular dependency with the "configuration" package.
	ConfigurationsInverseTable = "configurations"
	// ConfigurationsColumn is the table column denoting the configurations relation/edge.
	ConfigurationsColumn = "configuration_parent"
)

// Columns holds all SQL columns for branch fields.
var Columns = []string{
	FieldID,
	FieldBranchID,
	FieldName,
	FieldDescription,
	FieldIsDefault,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BranchIDValidator is a validator for the "branchID" field. It is called by the builders before save.
	BranchIDValidator func(int) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)
