name: 'Release: Buffer API/Worker'

on:
  push:
    tags:
      - 'buffer-v**'

env:
  # DockerHub login
  DOCKERHUB_USER: "keboolabot"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # For both images
  IMAGE_TAG: ${{ github.ref_name }}
  ECR_REGION: "us-east-1"
  ACR_REGISTRY: "keboola.azurecr.io"
  GCP_REGISTRY: "us-central1-docker.pkg.dev"
  GCP_IDENTITY_PROVIDER: "projects/388088979044/locations/global/workloadIdentityPools/github/providers/github"
  GCP_SERVICE_ACCOUNT: "keboola-as-code-ci-push@keboola-prod-artifacts.iam.gserviceaccount.com"

  # API image
  API_IMAGE_NAME: "keboola/buffer-api"
  API_ECR_REPOSITORY: "keboola/buffer-api"
  API_ECR_PUSH_ROLE: "arn:aws:iam::968984773589:role/kbc-ecr-BufferApiPushRole-8SI5TUN6TV99"
  API_GCP_REPOSITORY: "keboola-prod-artifacts/keboola-as-code/buffer-api"
  API_ACR_REPOSITORY: "buffer-api"
  API_ACR_USERNAME: "buffer-api-push"

  # Worker image
  WORKER_IMAGE_NAME: "keboola/buffer-worker"
  WORKER_ECR_REPOSITORY: "keboola/buffer-worker"
  WORKER_ECR_PUSH_ROLE: "arn:aws:iam::968984773589:role/kbc-ecr-BufferWorkerPushRole-15AMFOJ64KHB9"
  WORKER_GCP_REPOSITORY: "keboola-prod-artifacts/keboola-as-code/buffer-worker"
  WORKER_ACR_REPOSITORY: "buffer-worker"
  WORKER_ACR_USERNAME: "buffer-worker-push"

jobs:
  test-lint:
    name: "Lint"
    secrets: inherit
    uses: ./.github/workflows/test-lint.yml
  test-unit:
    name: "Unit Tests"
    secrets: inherit
    uses: ./.github/workflows/test-unit.yml
  test-e2e-service-buffer:
    name: "E2E: Buffer"
    secrets: inherit
    uses: ./.github/workflows/test-e2e-service-buffer.yml
  test-k8s-service-buffer:
    name: "K8S: Buffer"
    secrets: inherit
    uses: ./.github/workflows/test-k8s-service-buffer.yml
  build-and-push-api-image:
    name: "Build & Push API/Worker Images"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs:
      - test-lint
      - test-unit
      - test-e2e-service-buffer
      - test-k8s-service-buffer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build API image
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: ${{ env.API_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          context: .
          file: provisioning/stream/docker/api/Dockerfile

      - name: Build Worker image
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: ${{ env.WORKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          context: .
          file: provisioning/stream/docker/worker/Dockerfile

      - name: Push API image to Amazon ECR, Azure ACR and GCP GAR
        uses: ./.github/actions/push-image-aws-azure-gcp
        with:
          imageName: ${{ env.API_IMAGE_NAME }}
          imageTag: ${{ env.IMAGE_TAG }}
          ecrRegion: ${{ env.ECR_REGION }}
          ecrRepository: ${{ env.API_ECR_REPOSITORY }}
          ecrPushRole: ${{ env.API_ECR_PUSH_ROLE }}
          gcpRegistry: ${{ env.GCP_REGISTRY }}
          gcpRepository: ${{ env.API_GCP_REPOSITORY }}
          gcpIdentityProvider: ${{ env.GCP_IDENTITY_PROVIDER }}
          gcpServiceAccount: ${{ env.GCP_SERVICE_ACCOUNT }}
          acrRegistry: ${{ env.ACR_REGISTRY }}
          acrRepository: ${{ env.API_ACR_REPOSITORY }}
          acrUsername: ${{ env.API_ACR_USERNAME }}
          acrPassword: ${{ secrets.BUFFER_API_ACR_PASSWORD }}

      - name: Push Worker image to Amazon ECR, Azure ACR and GCP GAR
        uses: ./.github/actions/push-image-aws-azure-gcp
        with:
          imageName: ${{ env.WORKER_IMAGE_NAME }}
          imageTag: ${{ env.IMAGE_TAG }}
          ecrRegion: ${{ env.ECR_REGION }}
          ecrRepository: ${{ env.WORKER_ECR_REPOSITORY }}
          ecrPushRole: ${{ env.WORKER_ECR_PUSH_ROLE }}
          gcpRegistry: ${{ env.GCP_REGISTRY }}
          gcpRepository: ${{ env.WORKER_GCP_REPOSITORY }}
          gcpIdentityProvider: ${{ env.GCP_IDENTITY_PROVIDER }}
          gcpServiceAccount: ${{ env.GCP_SERVICE_ACCOUNT }}
          acrRegistry: ${{ env.ACR_REGISTRY }}
          acrRepository: ${{ env.WORKER_ACR_REPOSITORY }}
          acrUsername: ${{ env.WORKER_ACR_USERNAME }}
          acrPassword: ${{ secrets.BUFFER_WORKER_ACR_PASSWORD }}
