name: 'Load Go tools cache'
description: 'Load Go tools cache'
inputs:
  aws-s3-bucket:
    description: Bucket to save cache
    required: true
  aws-access-key-id:
    description: Access key to AWS
    required: true
  aws-secret-access-key:
    description: Secret access key to AWS
    required: true
runs:
  using: "composite"
  steps:
    - name: Use GNU tar instead BSD tar
      if: runner.os == 'Windows'
      shell: bash
      run: echo 'C:\Program Files\Git\usr\bin' >> $GITHUB_PATH

    - name: Load Go tools cache
      uses: ./.github/actions/go-cache
      with:
        key: tools
        with-variant-keys: false
        aws-s3-bucket: ${{ inputs.aws-s3-bucket }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        windows_go_cache_folder: ${{ github.workspace }}

    - name: Install Go modules
      shell: bash
      run: go mod download

    - name: Install tools
      run: . ./scripts/tools.sh
      shell: bash

